//定义变量  表示接口根地址 加api表示接口地址 接口地址都要带这个前缀
@url = http://localhost:3001/api
@json=Content-Type: application/json 

### 所以用户
get {{url}}/users
### 注册
post {{url}}/register
{{json}}
//有空行 表示请求体 下边写严格模式的json 
//请求头

{
    "tel":"10000000000",
    "pass":"1234561"
}
### 登录
post {{url}}/login
{{json}}

